# Generated by Django 4.0.10 on 2024-03-21 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="sat_dec_uncert_deg",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="sat_ra_uncert_deg",
        ),
        migrations.AddField(
            model_name="observation",
            name="sat_ra_dec_uncert_deg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(blank=True, default=0, null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
