# Generated by Django 4.0.10 on 2024-04-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0002_remove_observation_sat_dec_uncert_deg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="distance_to_sat_km",
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name="observation",
            name="height_above_ground_km",
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name="observation",
            name="phase_angle",
            field=models.FloatField(default=-1),
        ),
    ]
