# Generated by Django 4.0.10 on 2024-04-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0004_remove_observation_distance_to_sat_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="alt_deg_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="az_deg_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="ddec_deg_s_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="dra_cosdec_deg_s_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="illuminated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="limiting_magnitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="phase_angle",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="range_rate_sat_km_s_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="range_to_sat_km_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="sat_dec_deg_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="sat_ra_deg_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
