# Generated by Django 4.0.10 on 2024-04-16 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0005_alter_observation_alt_deg_satchecker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="obs_lat_deg",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="obs_long_deg",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="data_archive_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="repository.location",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="satellite_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="repository.satellite",
            ),
        ),
        migrations.AlterField(
            model_name="satellite",
            name="sat_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
