# Generated by Django 4.0.10 on 2024-04-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0006_alter_location_obs_lat_deg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="mpc_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
