# Generated by Django 4.0.10 on 2024-05-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0007_observation_mpc_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="sat_ra_dec_uncert_deg",
        ),
        migrations.AddField(
            model_name="observation",
            name="sigma_2_dec",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="sigma_2_ra",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="sigma_ra_sigma_dec",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
