# Generated by Django 4.0.10 on 2024-05-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0008_remove_observation_sat_ra_dec_uncert_deg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="sigma_2_dec",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="sigma_2_ra",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observation",
            name="sigma_ra_sigma_dec",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
