# Generated by Django 4.0.10 on 2024-06-17 19:19

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models

import repository.models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0009_alter_observation_sigma_2_dec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="apparent_mag_uncert",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="obs_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="observation",
            name="obs_orc_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=19),
                default=list,
                size=None,
                validators=[repository.models.validate_orcid],
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="obs_time_uncert_sec",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="range_to_sat_km",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="range_to_sat_uncert_km",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="sat_dec_deg",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="sat_ra_deg",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(360),
                ],
            ),
        ),
    ]
