# Generated by Django 4.0.10 on 2024-07-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0010_alter_observation_apparent_mag_uncert_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="satellite",
            unique_together={("sat_name", "sat_number")},
        ),
    ]
