# Generated by Django 4.2.16 on 2024-09-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0011_alter_satellite_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="intl_designator",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
