# Generated by Django 4.2.16 on 2024-09-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0012_satellite_intl_designator"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="decay_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="satellite",
            name="launch_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="satellite",
            name="object_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="satellite",
            name="rcs_size",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
