# Generated by Django 4.2.16 on 2025-04-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0013_satellite_decay_date_satellite_launch_date_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["satellite_id", "obs_time_utc"],
                name="observation_satelli_3eb165_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["satellite_id", "-obs_time_utc"],
                name="observation_satelli_cfe22f_idx",
            ),
        ),
    ]
