# Generated by Django 4.2.16 on 2025-07-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0014_observation_observation_satelli_3eb165_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="flag",
        ),
        migrations.AddField(
            model_name="observation",
            name="potentially_discrepant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
