# Generated by Django 4.2.16 on 2025-08-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0015_remove_observation_flag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="sat_altitude_km_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="solar_azimuth_deg_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="solar_elevation_deg_satchecker",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
