# Generated by Django 4.2.16 on 2025-11-26 05:12

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0016_observation_sat_altitude_km_satchecker_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKeyVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email for the key holder", max_length=254
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the key holder", max_length=200
                    ),
                ),
                (
                    "orcid_id",
                    models.CharField(
                        help_text="ORCID ID of the key holder", max_length=19
                    ),
                ),
                (
                    "verification_token",
                    models.UUIDField(
                        default=uuid.uuid4, help_text="Verification token"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Key Verification",
                "verbose_name_plural": "API Key Verifications",
                "db_table": "api_key_verification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("key_prefix", models.CharField(db_index=True, max_length=8)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the API key holder (person or organization)",
                        max_length=200,
                    ),
                ),
                (
                    "orcid_id",
                    models.CharField(
                        help_text="ORCID ID of the key holder", max_length=19
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Contact email for the key holder", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for the key",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the key is currently active"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this key has been used"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this key"
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_key",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="api_key_is_acti_d52b22_idx",
                    )
                ],
            },
        ),
    ]
