# Generated by Django 5.2.16 on 2026-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repository", "0017_apikeyverification_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="satellite",
            name="generation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
