ARG SETTINGS=score.settings.production
FROM --platform=linux/amd64 python:3.11

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
ARG SETTINGS
ENV DJANGO_SETTINGS_MODULE=${SETTINGS}
RUN celery --version
CMD ["celery", "-A", "score", "worker", "--loglevel=info"]
