name: Sonarless
on: push
jobs:
  Sonarless-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sonarless Scan
        uses: gitricko/sonarless@v1.2
        with:
          sonar-source-path: 'repository'

      - name: Print SonarQube metrics to logs
        run: cat ./sonar-metrics.json
